[2025-03-12T01:32:31.050+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-03-12T01:32:30.107351+00:00 [queued]>
[2025-03-12T01:32:31.058+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-03-12T01:32:30.107351+00:00 [queued]>
[2025-03-12T01:32:31.059+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-03-12T01:32:31.059+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-03-12T01:32:31.059+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-03-12T01:32:31.072+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2025-03-12 01:32:30.107351+00:00
[2025-03-12T01:32:31.078+0000] {standard_task_runner.py:55} INFO - Started process 1930 to run task
[2025-03-12T01:32:31.081+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2025-03-12T01:32:30.107351+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp1mcqhusm']
[2025-03-12T01:32:31.082+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask create_table
[2025-03-12T01:32:31.137+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2025-03-12T01:32:30.107351+00:00 [running]> on host 8c3ee0f87cd8
[2025-03-12T01:32:31.194+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-03-12T01:32:30.107351+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-12T01:32:30.107351+00:00
[2025-03-12T01:32:31.202+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-03-12T01:32:31.205+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2025-03-12T01:32:31.216+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(users, 2200) already exists.

[2025-03-12T01:32:31.223+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=create_table, execution_date=20250312T013230, start_date=20250312T013231, end_date=20250312T013231
[2025-03-12T01:32:31.234+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task create_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(users, 2200) already exists.
; 1930)
[2025-03-12T01:32:31.253+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2025-03-12T01:32:31.269+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
